# syntax=docker/dockerfile:latest
FROM alpine:3.23.4

RUN set -ex; \
    apk upgrade --no-cache -a

LABEL org.opencontainers.image.title="Alpine Base for Nextcloud AIO" 
    org.opencontainers.image.description="Minimal Alpine Linux base image for Nextcloud All-in-One" 
    org.opencontainers.image.url="https://github.com/nextcloud/all-in-one" 
    org.opencontainers.image.source="https://github.com/nextcloud/all-in-one" 
    org.opencontainers.image.vendor="Nextcloud" 
    org.opencontainers.image.documentation="https://github.com/nextcloud/all-in-one/blob/main/readme.md"
