<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitAllInOne
{
    public static $prefixLengthsPsr4 = array (
        'O' => 
        array (
            'OCA\\AllInOne\\' => 13,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'OCA\\AllInOne\\' => 
        array (
            0 => __DIR__ . '/..' . '/../lib',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'OCA\\AllInOne\\Settings\\Admin' => __DIR__ . '/..' . '/../lib/Settings/Admin.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitAllInOne::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitAllInOne::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitAllInOne::$classMap;

        }, null, ClassLoader::class);
    }
}
