#!/usr/bin/env bash
# =============================================================================
# CoreConduit Consulting Services
# Ubuntu 24.04 LTS — Ollama LLM Server Setup Script
# Target:  NVIDIA RTX 5070 (Blackwell / GB205)
# Config:  SSH hardening · NVIDIA drivers · CUDA · Ollama · UFW · LAN exposure
# Author:  Cory @ CoreConduit
# Version: 1.0.0
# =============================================================================

set -euo pipefail

# ── Colors ────────────────────────────────────────────────────────────────────
RED='\033[0;31m'; YELLOW='\033[1;33m'; GREEN='\033[0;32m'
CYAN='\033[0;36m'; BOLD='\033[1m'; RESET='\033[0m'

# ── Logging helpers ───────────────────────────────────────────────────────────
info()    { echo -e "${CYAN}[INFO]${RESET}  $*"; }
success() { echo -e "${GREEN}[OK]${RESET}    $*"; }
warn()    { echo -e "${YELLOW}[WARN]${RESET}  $*"; }
error()   { echo -e "${RED}[ERROR]${RESET} $*" >&2; exit 1; }
section() { echo -e "\n${BOLD}${CYAN}══════════════════════════════════════════${RESET}"; \
            echo -e "${BOLD}${CYAN}  $*${RESET}"; \
            echo -e "${BOLD}${CYAN}══════════════════════════════════════════${RESET}"; }

# ── Root check ────────────────────────────────────────────────────────────────
[[ $EUID -ne 0 ]] && error "Run this script as root:  sudo bash $0"

# ── Configuration — Edit these before running ─────────────────────────────────
SSH_PORT=2222                        # Change your SSH port (avoid 22)
SSH_PUBKEY=""                        # Paste your public key here (REQUIRED for key auth)
ADMIN_USER="${SUDO_USER:-$(logname 2>/dev/null || echo ubuntu)}"
OLLAMA_HOST="0.0.0.0"               # Bind to all interfaces for LAN access
OLLAMA_PORT=11434
LAN_SUBNET="192.168.1.0/24"         # ← EDIT to match your actual LAN subnet
NVIDIA_DRIVER_BRANCH="570"          # RTX 5070 (Blackwell) requires 570+
LOG_FILE="/var/log/coreconduit_setup.log"

# ── Sanity checks ─────────────────────────────────────────────────────────────
validate_config() {
  section "Validating Configuration"

  if [[ -z "$SSH_PUBKEY" ]]; then
    warn "SSH_PUBKEY is empty."
    warn "Password authentication will remain enabled until you add your key."
    warn "Edit this script and set SSH_PUBKEY before running for full hardening."
    PUBKEY_SET=false
  else
    PUBKEY_SET=true
  fi

  if [[ "$LAN_SUBNET" == "192.168.1.0/24" ]]; then
    warn "LAN_SUBNET is set to default (192.168.1.0/24)."
    warn "Verify this matches your network before running."
  fi

  info "Admin user  : $ADMIN_USER"
  info "SSH port    : $SSH_PORT"
  info "Ollama bind : $OLLAMA_HOST:$OLLAMA_PORT"
  info "LAN subnet  : $LAN_SUBNET"
  info "Log file    : $LOG_FILE"
}

# ── System update ─────────────────────────────────────────────────────────────
system_update() {
  section "System Update & Essential Packages"

  export DEBIAN_FRONTEND=noninteractive

  info "Running apt-get update..."
  apt-get update 2>&1 | tee -a "$LOG_FILE"

  info "Running apt-get upgrade..."
  DEBIAN_PRIORITY=critical apt-get upgrade -y -o Dpkg::Pre-Install-Pkgs::Hold="" 2>&1 | tee -a "$LOG_FILE" || true

  info "Installing essential packages..."
  apt-get install -y \
    curl wget git vim htop tmux \
    build-essential dkms \
    ufw fail2ban \
    net-tools lsof \
    software-properties-common \
    apt-transport-https ca-certificates \
    pciutils "linux-headers-$(uname -r)" \
    2>&1 | tee -a "$LOG_FILE" || warn "Some packages had issues but continuing..."

  success "System updated and base packages installed."
}

# ── SSH Hardening ─────────────────────────────────────────────────────────────
harden_ssh() {
  section "SSH Hardening"

  SSHD_CONFIG="/etc/ssh/sshd_config"
  cp "$SSHD_CONFIG" "${SSHD_CONFIG}.bak.$(date +%F)"
  info "Backed up sshd_config."

  # Install public key for admin user
  if [[ "$PUBKEY_SET" == true ]]; then
    USER_HOME=$(eval echo "~$ADMIN_USER")
    SSH_DIR="$USER_HOME/.ssh"
    mkdir -p "$SSH_DIR"
    echo "$SSH_PUBKEY" >> "$SSH_DIR/authorized_keys"
    chmod 700 "$SSH_DIR"
    chmod 600 "$SSH_DIR/authorized_keys"
    chown -R "$ADMIN_USER:$ADMIN_USER" "$SSH_DIR"
    success "SSH public key installed for $ADMIN_USER."
  fi

  # Write hardened sshd_config
  cat > "$SSHD_CONFIG" <<EOF
# ── CoreConduit Hardened SSH Configuration ──────────────────────────────────
# Generated by coreconduit_server_setup.sh

Port $SSH_PORT
AddressFamily inet
ListenAddress 0.0.0.0

# ── Authentication ──────────────────────────────────────────────────────────
LoginGraceTime 30
PermitRootLogin no
StrictModes yes
MaxAuthTries 4
MaxSessions 5

PubkeyAuthentication yes
AuthorizedKeysFile .ssh/authorized_keys

# Disable password auth only when a key has been configured
$(if [[ "$PUBKEY_SET" == true ]]; then echo "PasswordAuthentication no"; else echo "PasswordAuthentication yes  # TEMP: add SSH_PUBKEY and re-run to disable"; fi)
PermitEmptyPasswords no
ChallengeResponseAuthentication no
KbdInteractiveAuthentication no
UsePAM yes

# ── Forwarding & Tunneling ──────────────────────────────────────────────────
AllowAgentForwarding no
AllowTcpForwarding no
X11Forwarding no
PrintMotd no

# ── Session hardening ───────────────────────────────────────────────────────
ClientAliveInterval 300
ClientAliveCountMax 2
TCPKeepAlive no

# ── Logging ─────────────────────────────────────────────────────────────────
SyslogFacility AUTH
LogLevel VERBOSE

# ── Allowed users ───────────────────────────────────────────────────────────
AllowUsers $ADMIN_USER

# ── Ciphers & MACs (modern hardened set) ────────────────────────────────────
Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com
MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com
KexAlgorithms curve25519-sha256,curve25519-sha256@libssh.org,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512

# ── Subsystems ──────────────────────────────────────────────────────────────
Subsystem sftp /usr/lib/openssh/sftp-server
EOF

  if sshd -t; then
    success "sshd_config validated."
    systemctl restart ssh
    success "SSH hardened on port $SSH_PORT."
  else
    error "sshd_config has syntax errors. Restoring backup from ${SSHD_CONFIG}.bak.$(date +%F)"
    cp "${SSHD_CONFIG}.bak.$(date +%F)" "$SSHD_CONFIG"
  fi
}

# ── Fail2Ban ──────────────────────────────────────────────────────────────────
configure_fail2ban() {
  section "Fail2Ban Configuration"

  cat > /etc/fail2ban/jail.local <<EOF
[DEFAULT]
bantime  = 1h
findtime  = 10m
maxretry = 5
backend = systemd

[sshd]
enabled  = true
port     = $SSH_PORT
filter   = sshd
logpath  = /var/log/auth.log
maxretry = 3
bantime  = 24h
EOF

  systemctl enable --now fail2ban
  success "Fail2Ban configured (SSH jail on port $SSH_PORT, 3 retries, 24h ban)."
}

# ── UFW Firewall ──────────────────────────────────────────────────────────────
configure_ufw() {
  section "UFW Firewall Rules"

  ufw --force reset
  ufw default deny incoming
  ufw default allow outgoing

  # SSH on custom port
  ufw allow "$SSH_PORT/tcp" comment "SSH (CoreConduit hardened)"

  # Ollama — LAN only
  ufw allow from "$LAN_SUBNET" to any port "$OLLAMA_PORT" proto tcp comment "Ollama API (LAN)"

  ufw --force enable
  ufw status verbose
  success "UFW enabled. Ollama port $OLLAMA_PORT open to $LAN_SUBNET only."
}

# ── NVIDIA Drivers (RTX 5070 / Blackwell) ────────────────────────────────────
install_nvidia() {
  section "NVIDIA Driver $NVIDIA_DRIVER_BRANCH (RTX 5070 / Blackwell)"

  # Check if GPU is detected
  if ! lspci | grep -qi nvidia; then
    warn "No NVIDIA GPU detected by lspci. Skipping driver install."
    warn "If the GPU is present, ensure PCIe is recognized and re-run."
    return
  fi

  # Clean up any conflicting packages
  apt-get autoremove -y 2>&1 | tee -a "$LOG_FILE" || true
  apt-get clean 2>&1 | tee -a "$LOG_FILE" || true

  # Add ubuntu-drivers and install
  apt-get install -y ubuntu-drivers-common 2>&1 | tee -a "$LOG_FILE"

  info "Installing nvidia-driver-${NVIDIA_DRIVER_BRANCH} (open kernel module)..."
  if ! apt-get install -y \
    "nvidia-driver-${NVIDIA_DRIVER_BRANCH}-open" \
    nvidia-cuda-toolkit \
    nvidia-utils-${NVIDIA_DRIVER_BRANCH} \
    2>&1 | tee -a "$LOG_FILE"; then
    warn "NVIDIA driver installation encountered issues. Attempting fix-broken..."
    apt-get install --fix-broken -y 2>&1 | tee -a "$LOG_FILE" || \
      warn "Could not auto-fix broken packages. Manual intervention may be needed."
  fi

  # Blacklist nouveau
  cat > /etc/modprobe.d/blacklist-nouveau.conf <<EOF
blacklist nouveau
options nouveau modeset=0
EOF
  update-initramfs -u 2>&1 | tee -a "$LOG_FILE"

  success "NVIDIA driver ${NVIDIA_DRIVER_BRANCH} installed. A reboot is required before Ollama GPU verification."
  REBOOT_REQUIRED=true
}

# ── Ollama ────────────────────────────────────────────────────────────────────
install_ollama() {
  section "Ollama Installation & Configuration"

  # Install via official script
  info "Downloading and running Ollama installer..."
  curl -fsSL https://ollama.com/install.sh | sh 2>&1 | tee -a "$LOG_FILE"

  # Configure Ollama systemd service for LAN binding
  mkdir -p /etc/systemd/system/ollama.service.d
  cat > /etc/systemd/system/ollama.service.d/override.conf <<EOF
[Service]
Environment="OLLAMA_HOST=${OLLAMA_HOST}:${OLLAMA_PORT}"
Environment="OLLAMA_ORIGINS=*"
# Uncomment to limit VRAM per model (MB):
# Environment="OLLAMA_MAX_VRAM=10240"
# Uncomment to set max loaded models:
# Environment="OLLAMA_MAX_LOADED_MODELS=2"
# Uncomment to enable verbose logging:
# Environment="OLLAMA_DEBUG=1"
EOF

  systemctl daemon-reload
  systemctl enable --now ollama
  success "Ollama installed and running on ${OLLAMA_HOST}:${OLLAMA_PORT}."

  # Wait for API to be ready
  info "Waiting for Ollama API to become ready..."
  for _ in {1..10}; do
    if curl -sf "http://localhost:${OLLAMA_PORT}/api/tags" > /dev/null 2>&1; then
      success "Ollama API is responding."
      break
    fi
    sleep 2
  done
}

# ── MOTD / Login Banner ───────────────────────────────────────────────────────
configure_motd() {
  section "Login Banner (MOTD)"

  # Disable default Ubuntu dynamic MOTD noise
  chmod -x /etc/update-motd.d/* 2>/dev/null || true

  cat > /etc/motd <<'EOF'

  ╔══════════════════════════════════════════════════════╗
  ║          CoreConduit Consulting Services             ║
  ║          Ollama LLM Server · Ubuntu 24.04            ║
  ╠══════════════════════════════════════════════════════╣
  ║  Unauthorized access is prohibited.                  ║
  ║  All sessions are logged.                            ║
  ╚══════════════════════════════════════════════════════╝

EOF
  success "Login banner configured."
}

# ── System hardening extras ───────────────────────────────────────────────────
system_hardening() {
  section "Additional System Hardening"

  # Disable core dumps
  cat >> /etc/security/limits.conf <<'EOF'
* hard core 0
EOF

  # Kernel hardening via sysctl
  cat > /etc/sysctl.d/99-coreconduit-hardening.conf <<'EOF'
# CoreConduit Kernel Hardening

# Prevent IP spoofing
net.ipv4.conf.all.rp_filter = 1
net.ipv4.conf.default.rp_filter = 1

# Ignore ICMP broadcast requests
net.ipv4.icmp_echo_ignore_broadcasts = 1

# Disable source packet routing
net.ipv4.conf.all.accept_source_route = 0
net.ipv6.conf.all.accept_source_route = 0

# Ignore send redirects
net.ipv4.conf.all.send_redirects = 0

# Block SYN attacks
net.ipv4.tcp_syncookies = 1
net.ipv4.tcp_max_syn_backlog = 2048
net.ipv4.tcp_synack_retries = 2
net.ipv4.tcp_syn_retries = 5

# Log spoofed, source-routed, and redirect packets
net.ipv4.conf.all.log_martians = 1

# Disable IPv6 if not needed (comment out to keep IPv6)
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
EOF

  sysctl --system 2>&1 | tee -a "$LOG_FILE"
  success "Kernel hardening parameters applied."
}

# ── Verification summary ──────────────────────────────────────────────────────
verify_setup() {
  section "Verification Summary"

  echo -e "\n${BOLD}── Services ─────────────────────────────────────────────${RESET}"
  for svc in ssh fail2ban ufw ollama; do
    status=$(systemctl is-active "$svc" 2>/dev/null || echo "inactive")
    if [[ "$status" == "active" ]]; then
      echo -e "  ${GREEN}●${RESET} $svc"
    else
      echo -e "  ${RED}●${RESET} $svc ($status)"
    fi
  done

  echo -e "\n${BOLD}── UFW Status ───────────────────────────────────────────${RESET}"
  ufw status numbered

  echo -e "\n${BOLD}── Ollama API ───────────────────────────────────────────${RESET}"
  if curl -sf "http://localhost:${OLLAMA_PORT}/api/tags" > /dev/null 2>&1; then
    echo -e "  ${GREEN}●${RESET} Ollama API responding at localhost:${OLLAMA_PORT}"
  else
    echo -e "  ${YELLOW}●${RESET} Ollama API not yet responding (may need reboot for GPU)"
  fi

  echo -e "\n${BOLD}── NVIDIA GPU ───────────────────────────────────────────${RESET}"
  if command -v nvidia-smi &>/dev/null; then
    nvidia-smi --query-gpu=name,driver_version,memory.total --format=csv,noheader 2>/dev/null \
      && success "nvidia-smi OK" \
      || warn "nvidia-smi present but GPU may not be loaded yet — reboot required."
  else
    warn "nvidia-smi not found — reboot may be needed to load drivers."
  fi

  echo ""
}

# ── Post-install notes ────────────────────────────────────────────────────────
print_notes() {
  section "Post-Install Notes"

  echo -e "${BOLD}Next steps:${RESET}"
  echo ""
  echo -e "  1. ${YELLOW}REBOOT${RESET} to load NVIDIA drivers:"
  echo -e "     ${CYAN}sudo reboot${RESET}"
  echo ""
  echo -e "  2. After reboot, verify GPU:"
  echo -e "     ${CYAN}nvidia-smi${RESET}"
  echo ""
  echo -e "  3. Pull a model (example — Qwen3.5 0.8B for edge):"
  echo -e "     ${CYAN}ollama pull qwen2.5:0.5b${RESET}"
  echo -e "     ${CYAN}ollama pull qwen2.5:7b${RESET}"
  echo ""
  echo -e "  4. Test Ollama API from LAN client (NEXUS):"
  echo -e "     ${CYAN}curl http://<SERVER_IP>:${OLLAMA_PORT}/api/tags${RESET}"
  echo ""
  echo -e "  5. SSH to this server going forward:"
  echo -e "     ${CYAN}ssh -p ${SSH_PORT} ${ADMIN_USER}@<SERVER_IP>${RESET}"
  echo ""
  if [[ "$PUBKEY_SET" == false ]]; then
    echo -e "  ${RED}⚠  ACTION REQUIRED:${RESET} Add your SSH public key to SSH_PUBKEY"
    echo -e "     in this script and re-run to disable password authentication."
    echo ""
  fi
  echo -e "  Setup log: ${CYAN}$LOG_FILE${RESET}"
  echo ""
}

# ── Main ──────────────────────────────────────────────────────────────────────
main() {
  REBOOT_REQUIRED=false
  exec > >(tee -a "$LOG_FILE") 2>&1

  echo -e "\n${BOLD}${CYAN}"
  echo "  ╔══════════════════════════════════════════════════════╗"
  echo "  ║   CoreConduit — Ollama LLM Server Setup v1.0.0      ║"
  echo "  ║   Ubuntu 24.04 · RTX 5070 · $(date '+%Y-%m-%d %H:%M')          ║"
  echo "  ╚══════════════════════════════════════════════════════╝"
  echo -e "${RESET}"

  validate_config
  system_update
  harden_ssh
  configure_fail2ban
  system_hardening
  configure_ufw
  install_nvidia
  install_ollama
  configure_motd
  verify_setup
  print_notes

  if [[ "$REBOOT_REQUIRED" == true ]]; then
    echo -e "${YELLOW}[REBOOT REQUIRED]${RESET} Run: ${CYAN}sudo reboot${RESET}\n"
  fi
}

main "$@"
