name: 'Lock Threads'

on:
  schedule:
    - cron: '0 0 * * *'

permissions:
  issues: write

concurrency:
  group: lock

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/lock-threads@851cffe46851ddd2051ea7147ebdc995113241c3 # v5
        with: 
          issue-inactive-days: '14'
          process-only: 'issues'
